# Generated by Django 2.2.14 on 2020-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('slot', models.IntegerField(null=True)),
                ('started', models.DateField(null=True)),
                ('completed', models.DateField(null=True)),
            ],
            options={
                'db_table': 'operations',
            },
        ),
    ]
