# Generated by Django 2.2.14 on 2021-01-24 20:05

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_project_grouping',
            field=models.CharField(choices=[['none', 'none'], ['status', 'status']], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='show_done_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(max_length=9)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Maintenance'), (3, 'On Hold'), (4, 'Not Started'), (5, 'Abandoned'), (6, 'Completed')], default=2)),
                ('creation_time', models.IntegerField(default=time.time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.User')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['creation_time'],
            },
        ),
    ]
