# Generated by Django 2.2.14 on 2021-01-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'Active'), (3, 'Maintenance'), (4, 'On Hold'), (5, 'Completed'), (6, 'Abandoned')], default=2),
        ),
    ]
