# Generated by Django 2.2.14 on 2020-12-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201203_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='slot_order',
            new_name='order',
        ),
    ]
